name: Market Insight Indonesia

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-system:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run Market Insight & Ekstrak Risk Engine
        id: market
        env:
          TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
        run: |
          npm start 2>&1 | tee output.txt
          {
            sed -n '/RISK ENGINE/,/Risk Reward/p' output.txt
            echo ""
            sed -n '/Status      : WAIT/,/Reason      : /p' output.txt | head -2
          } > risk.txt
          echo "RISK<<EOF" >> $GITHUB_ENV
          cat risk.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Dapatkan waktu
        run: echo "CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Kirim Risk Engine ke Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            📊 MARKET INSIGHT INDONESIA
            
            ⏰ Waktu: ${{ env.CURRENT_TIME }}
            ✅ Status: ${{ job.status }}
            
            ${{ env.RISK }}
